# Generated by Django 4.2 on 2026-06-01 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', message='Формат: +7XXXXXXXXXX')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('passport', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='10 цифр без пробелов')], verbose_name='Паспорт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.PositiveSmallIntegerField(verbose_name='Корпус')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('category', models.CharField(choices=[('std', 'Стандарт'), ('semi', 'Полулюкс'), ('lux', 'Люкс')], max_length=10, verbose_name='Категория')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='Вместимость')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ночь')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('cleaning', 'Уборка'), ('maintenance', 'Ремонт')], default='free', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('meal_plan', models.CharField(choices=[('none', 'Без питания'), ('breakfast', 'Завтрак'), ('full', 'Полный пансион')], default='none', max_length=10, verbose_name='Питание')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('checked_in', 'Заселено'), ('checked_out', 'Выехало'), ('cancelled', 'Отменено')], default='confirmed', max_length=15, verbose_name='Статус')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Гость')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата начисления')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.booking', verbose_name='Бронь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Начисление услуги',
                'verbose_name_plural': 'Начисления услуг',
            },
        ),
    ]
